name: tests-pr

on:
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-asyncio discord

    - name: Run unit tests
      run: |
        pytest -vvv .
    
    - name: Coverage report
      run: |
        echo "\`\`\`\nCoverage:\n" > cov.txt
        pytest --cov=src . | sed "1,/coverage: /d" | sed "/^\=/d" >> cov.txt
        echo "\`\`\`\\n" >> cov.txt

    - name: Comment coverage
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: cov.txt
      
